### ISSUE TITLE
Refactor this API to easily fetch resources

### ISSUE THREAD

**Issue by ronaldtse** [relaton/w3c_api#2]
From:
* https://github.com/relaton/relaton-w3c/issues/44#issuecomment-2704973012

From @andrew2net 

As discussed with @ronaldtse the API gives as
```yaml
$ w3c_api specification fetch --shortname=webrtc --format=yaml
---
shortlink: https://www.w3.org/TR/webrtc/
description: "<p>This document defines a set of ECMAScript APIs in WebIDL to allow
  media to be sent to and received from another browser or device implementing the
  appropriate set of real-time protocols. This specification is being developed in
  conjunction with a protocol specification developed by the IETF RTCWEB group and
  an API specification to get access to local media devices.</p>"
title: 'WebRTC: Real-Time Communication in Browsers'
shortname: webrtc
editor_draft: https://w3c.github.io/webrtc-pc/
series_version: '1.0'
_links:
  self:
    href: https://api.w3.org/specifications/webrtc
  version_history:
    href: https://api.w3.org/specifications/webrtc/versions
  first_version:
    href: https://api.w3.org/specifications/webrtc/versions/20111027
    title: Working Draft
  latest_version:
    href: https://api.w3.org/specifications/webrtc/versions/20241008
    title: Recommendation
  series:
    href: https://api.w3.org/specification-series/webrtc
```
From the response we can obtain
-  shortlink => source
- description = > abstract
- title => title
- shortname => ID
- series_version => series/number
- version_history => relations
- TR from the shortlink => doctype (technicalReport)

For versioned documents the API additionaly provides
```yaml
$ w3c_api specification fetch --shortname=webrtc --version=20111027
---
status: Working Draft
rec_track: true
editor_draft: https://w3c.github.io/webrtc-pc/
uri: https://www.w3.org/TR/2011/WD-webrtc-20111027/
date: '2011-10-27T00:00:00+00:00'
informative: false
title: 'WebRTC 1.0: Real-time Communication Between Browsers'
shortlink: https://www.w3.org/TR/webrtc/
_links:
  self:
    href: https://api.w3.org/specifications/webrtc/versions/20111027
  specification:
    href: https://api.w3.org/specifications/webrtc
```
- status
  - Working Draft => W3C WD {ID}
  - Recommendation => W3C REC {ID}
- date => date[@type="published"]

The https://api.w3.org/doc also has “editors” and “deliverers” endpoints but I didn't fid such functionality in the https://github.com/relaton/w3c_api gem. @ronaldtse  should I implement fetching “editors” and “deliverers” in w3c_api?
